#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
import sys
import select
import tty
import termios

# Keymap settings for standard Arrow keys and Holonomic strafing
# Arrow keys map to standard terminal ANSI escape codes (\x1b[A, \x1b[B, etc.)
KEY_MAP = {
    '\x1b[A': (0.3, 0.0, 0.0),   # UP ARROW    : Forward (+X)
    '\x1b[B': (-0.3, 0.0, 0.0),  # DOWN ARROW  : Backward (-X)
    '\x1b[D': (0.0, 0.0, 0.5),   # LEFT ARROW  : Turn Left (+Yaw)
    '\x1b[C': (0.0, 0.0, -0.5),  # RIGHT ARROW : Turn Right (-Yaw)
    
    # Optional Strafing (Holonomic Y-axis) using 'a' and 'd'
    'a': (0.0, 0.2, 0.0),        # 'A' key     : Strafe Left (+Y)
    'd': (0.0, -0.2, 0.0),       # 'D' key     : Strafe Right (-Y)
}

USAGE_MSG = """
---------------------------------------------
🎮 Caddie Go2 Arrow Key Teleop Controller 🎮
---------------------------------------------
Moving around:
       ▲ (Up)    : Forward
       ▼ (Down)  : Backward
   ◀ (Left) / (Right) ▶ : Turn Left / Right

Strafing (Y-axis):
   'a' : Strafe Left
   'd' : Strafe Right

SPACEBAR or any other key : Stop
CTRL-C to quit
---------------------------------------------
"""

def get_key(settings):
    """ Reads raw keyboard presses without requiring ENTER """
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
        # Handle 3-byte escape sequences generated by arrow keys
        if key == '\x1b':
            key += sys.stdin.read(2)
    else:
        key = ''
    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key

def main(args=None):
    rclpy.init(args=args)
    node = rclpy.create_node('teleop_arrows')
    pub = node.create_publisher(Twist, '/cmd_vel', 10)
    
    settings = termios.tcgetattr(sys.stdin)
    print(USAGE_MSG)

    speed_step = 1.0
    
    try:
        while rclpy.ok():
            key = get_key(settings)
            twist = Twist()

            if key in KEY_MAP:
                vx, vy, wz = KEY_MAP[key]
                twist.linear.x = vx * speed_step
                twist.linear.y = vy * speed_step
                twist.angular.z = wz * speed_step
            elif key == ' ':
                twist.linear.x = 0.0
                twist.linear.y = 0.0
                twist.angular.z = 0.0
            elif key == '\x03':  # CTRL-C
                break
                
            pub.publish(twist)

    except Exception as e:
        print(e)

    finally:
        # Publish zero velocity on exit to stop the robot
        twist = Twist()
        pub.publish(twist)
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()