<?xml version="1.0"?>
<package format="3">
  <name>caddie_bringup</name>
  <version>0.1.0</version>
  <description>Top-level launch package for WSO2 Caddie simulation bringup.</description>
  <maintainer email="abdulr.23@cse.mrt.ac.lk">Team Talos</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>caddie_control</exec_depend>
  <exec_depend>caddie_core</exec_depend>
  <exec_depend>caddie_gazebo</exec_depend>
  <exec_depend>caddie_interaction</exec_depend>
  <exec_depend>caddie_navigation</exec_depend>
  <exec_depend>caddie_perception</exec_depend>
  <exec_depend>caddie_unitree_official</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
